# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOuTfPDLsli59zcB_PR3kVWC0lLvFgLW
"""

import pandas as pd
baza={
    "FISH":[ "G'aniyev Iqboljon" , "Muxtorov Murodil","Xolmatov Murodl","Mamasoliyev Asilbek","Usmonov Muhammadyusuf","Soliyev Sardor","Abdullayev SHaxriyor" ,"Topvoldiyev Abbosbek","Mirzaaliyev Azizjon","Oribjova Mubina"],
    "Yosh":[ "19","19","19","18","19","19","19","19","20","18",  ],
    "Maktabi":[ '27-maktab',"15-maktab","30-maktab","34-maktab","35-maktab","24-maktab","13-maktab ","28-maktab","13-maktab","35-maktab"],
    "jinsi":[ 'erkak','erkak','erkak','erkak','erkak','erkak','erkak','erkak','erkak','erkak', ] ,
    "Manzili":[  "Buvayda tumani","Uchkoprik Tumani","Uchkoprik Tumani","Furqat tumani","kosonsoy tumani","pop tumani","beshariq tumani","farg'ona tumani","O'zbekiston tumani","Qorgontepa tumani"],
}
malumot=pd.DataFrame(baza)
print(malumot)

filtr=malumot[(malumot['Yosh']=='19')&(malumot['jinsi']=="erkak")&(malumot['Manzili']=="pop tumani")]
print(filtr)